name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
       
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
         username: ${{ secrets.DOCKER_HUB_USER }}
         password: ${{ secrets.DOCKER_HUB_TOKEN }}
         
    - name: Build push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        push: true
        tags: "mayur21486/helloapp:${{ github.sha }}"
        
    - uses: actions/checkout@v3
      with:
         repository: 'mayur21486/argocd_deploy'
         ref: 'master'
    #     token: "{{ secrets.OWN_TOKEN }}"
     
    - name: update helm chart
      run: |
          ls -al 
          version=$(cat dev/deployment.yaml | grep image | awk -F: '{print $3}')
          sed -i "s/$version/${{ github.sha }}/" dev/deployment.yml
          git add dev/deployment.yml
          git commit -m "update image tag ${{ github.sha }}"
          
        
