name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git Commit Data
      uses: rlespinasse/git-commit-data-action@1.3.0
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Check outputs
      run: echo ${{ steps.vars.outputs.sha_short }}
        
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
         username: ${{ secrets.DOCKER_HUB_USER }}
         password: ${{ secrets.DOCKER_HUB_TOKEN }}
         
    - name: Build push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        push: true
        tags: "mayur21486/helloapp:${{ steps.vars.outputs.sha_short }}"
        
