name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
       
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
         username: ${{ secrets.DOCKER_HUB_USER }}
         password: ${{ secrets.DOCKER_HUB_TOKEN }}
         
    - name: Build push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        push: true
        tags: "mayur21486/helloapp:${{ github.sha }}"
        
     
    - name: update helm chart
      run: |
          git clone "{{ secrets.OWN_TOKEN }}"@github.com:mayur21486/argocd_deploy.git
          ls -al 
          version=$(cat deployment.yaml | grep image | awk -F: '{print $3}')
          sed -i "s/$version/${{ github.sha }}/" argocd_deploy/dev/deployment.yml
          git add argocd_deploy/dev/deployment.yml
          git commit -m "update image tag ${{ github.sha }}"
          
        
