name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git Commit Data
  # You may pin to the exact commit or the version.
  # uses: rlespinasse/git-commit-data-action@55e2409bbead4bfa5ae18c9dc7657f2576f9fe50
      uses: rlespinasse/git-commit-data-action@1.3.0
    
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
         username: ${{ secrets.DOCKER_HUB_USER }}
         password: ${{ secrets.DOCKER_HUB_TOKEN }}
         
    - name: Build push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        push: true
        tags: mayur21486/helloapp:"${{ env.GIT_COMMIT_SHORT_SHA }}"
        
