name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  Pre-Build:
    runs-on: ubuntu-latest
    steps:
    - name: test run
      run: |
         echo00 "Prebuild stage Mayur"
        
  build:

    runs-on: ubuntu-latest
#    if: ${{ always() }}
    needs: Pre-Build
    steps:
       
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
         username: ${{ secrets.DOCKER_HUB_USER }}
         password: ${{ secrets.DOCKER_HUB_TOKEN }}
         
    - name: Build push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        push: true
        tags: "mayur21486/helloapp:${{ github.sha }}"
        
    #- uses: actions/checkout@v3
     # with:
      #   repository: mayur21486/argocd_deploy
       #  ref: master
        # token: "{{ secrets.OWN_TOKEN }}"
    
    - uses: sudosubin/git-clone-action@v1.0.1
      with: 
         repository: mayur21486/argocd_deploy
         ref: master
     
    - name: update helm chart
      run: |
          ls -al 
          version=$(cat dev/deployment.yml | grep image | awk -F: '{print $3}')
          sed -i "s/$version/${{ github.sha }}/" dev/deployment.yml
          git add dev/deployment.yml
          git config --global user.email "mayur21486@gmail.com"
          git config --global user.name "mayur21486"
      #    git commit -m "update image tag ${{ github.sha }}"
     #     git push origin --all
      
    - uses: github-actions-x/commit@v2.9
      with:
          github-token: "${{ secrets.OWN_TOKEN }}"
          commit-message: "update image tag ${{ github.sha }}"
          files: dev/deployment.yml
          email: mayur21486@gmail.com
          name: mayur21486
          push-branch: master
          
         
        
